In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print(array1)
print(array1.shape)
print(type(array1))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [3]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2.shape)

(2, 3)


In [4]:
array3 = np.array([[1,2,3]])
print(array3.shape)

(1, 3)


In [5]:
array3.ndim

2

In [6]:
array3.dtype

dtype('int32')

In [7]:
list1 = [1,2.0,'test']
array4 = np.array(list1)
print(array4)

['1' '2.0' 'test']


In [12]:
print(array2.astype('str'))

[['1' '2' '3']
 ['4' '5' '6']]


In [17]:
print(np.arange(10))
print(np.zeros((3,2)))
print(np.ones((3,2)))

[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
print(np.arange(10).reshape(2,5).tolist())

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [24]:
a = np.arange(1,10)
b = a[0:3].copy()

In [25]:
print(b)

[1 2 3]


In [26]:
b[0] = 5
print(a)

[1 2 3 4 5 6 7 8 9]


In [32]:
arr = np.arange(9)
print(arr)
print(arr.reshape(3,3))
print(arr.reshape(3,3)[[0,2],0:2])

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [6 7]]


In [35]:
array1d = np.arange(1,10)
print(array1d>5)
print(array1d[array1d>5])

[False False False False False  True  True  True  True]
[6 7 8 9]


In [37]:
sarr = np.array([3,1,4,5])
print(sarr)
print(np.sort(sarr))
print(np.sort(sarr)[::-1])
print(sarr)
print(sarr.sort())
print(sarr)

[3 1 4 5]
[1 3 4 5]
[5 4 3 1]
[3 1 4 5]
None
[1 3 4 5]


In [40]:
org_arr = np.array([3,1,5,2])
sort_indices = np.argsort(org_arr)
print(sort_indices)

[1 3 0 2]


In [42]:
import pandas as pd
# in kaggle notebook

In [44]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [46]:
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [48]:
iris_data= iris.data
iris_label = iris.target
print(iris_label)
print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [49]:
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [64]:
x_train, x_test, y_train,y_test = train_test_split(iris_data,iris_label,test_size=0.2,random_state=726)

In [68]:
dt_clf = DecisionTreeClassifier(random_state=726)

In [69]:
dt_clf.fit(x_train,y_train)
pred = dt_clf.predict(x_test)

In [71]:
from sklearn.metrics import accuracy_score
print('Prediction Accuracy : {:.2f}%'.format(accuracy_score(y_test,pred)*100))

Prediction Accuracy : 86.67%


In [74]:
keys = iris.keys()
keys

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [78]:
x_train, x_test, y_train,y_test = train_test_split(iris.data,iris.target,\
                                                  test_size=.3,random_state=778)

In [82]:
dt_clf.fit(x_train,y_train)
pred = dt_clf.predict(x_test)
print('Pred Acc : {:.4f}'.format(accuracy_score(y_test,pred)))

Pred Acc : 1.0000


In [84]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features= iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy=[]
print(features.shape[0])

150


In [94]:
for x in kfold.split(features):
    print(x)
    print('='*100)

(array([ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))
(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  60,  61,  62,  63,

In [98]:
n_iter = 0
for train_index, test_index in kfold.split(features):
    x_train,x_test = features[train_index],features[test_index]
    y_train,y_test = label[train_index],label[test_index]
    
    dt_clf.fit(x_train,y_train)
    pred= dt_clf.predict(x_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print('\n#{0} CV Acc: {1}, train set size: {2}, test set size: {3}'.format(n_iter,accuracy,train_size,test_size))
    cv_accuracy.append(accuracy)

print('\n## Avg CV Acc: {:.4f}'.format(np.mean(cv_accuracy)))


#1 CV Acc: 1.0, train set size: 120, test set size: 30

#2 CV Acc: 0.9667, train set size: 120, test set size: 30

#3 CV Acc: 0.8667, train set size: 120, test set size: 30

#4 CV Acc: 0.9333, train set size: 120, test set size: 30

#5 CV Acc: 0.7333, train set size: 120, test set size: 30

## Avg CV Acc: 0.9000


In [99]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5)
n_iter = 0
for train_index, test_index in skf.split(iris_df,iris_df['label']):
    x_train,x_test = features[train_index],features[test_index]
    y_train,y_test = label[train_index],label[test_index]
    
    dt_clf.fit(x_train,y_train)
    pred= dt_clf.predict(x_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print('\n#{0} CV Acc: {1}, train set size: {2}, test set size: {3}'.format(n_iter,accuracy,train_size,test_size))
    cv_accuracy.append(accuracy)

print('\n## Avg CV Acc: {:.4f}'.format(np.mean(cv_accuracy)))


#1 CV Acc: 0.9667, train set size: 120, test set size: 30

#2 CV Acc: 0.9667, train set size: 120, test set size: 30

#3 CV Acc: 0.9, train set size: 120, test set size: 30

#4 CV Acc: 0.9667, train set size: 120, test set size: 30

#5 CV Acc: 1.0, train set size: 120, test set size: 30

## Avg CV Acc: 0.9150


In [103]:
from sklearn.model_selection import cross_val_score, cross_validate

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=157)
data = iris_data.data
label = iris_data.target
scores = cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('CV Acc: {}'.format(np.round(scores,4)))
print('Avg Acc: ',np.round(np.mean(scores),4))

CV Acc: [0.98 0.94 0.98]
Avg Acc:  0.9667


In [104]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris  = load_iris()
x_train,x_test ,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.1,random_state=157)
dtree = DecisionTreeClassifier()
grid_parameters = {'max_depth' : [1,2,3],'min_samples_split':[2,3]}

grid_dtree = GridSearchCV(dtree,param_grid=grid_parameters,cv=5,refit=True)
grid_dtree.fit(x_train,y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000799      0.000399         0.000600        0.000490   
1       0.000600      0.000490         0.001007        0.000009   
2       0.000796      0.000398         0.000200        0.000400   
3       0.000998      0.000002         0.000400        0.000490   
4       0.000599      0.000489         0.000601        0.000491   
5       0.000804      0.000402         0.000400        0.000490   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}           0.703704   
1  {'max_depth': 1, 'min_samples_split': 3}           0.703704   
2  {'max_depth': 2, 'min_samples_split': 2}           1.000000   
3  {'max_depth': 2, 'min_samples_split': 3}           1.000000   
4  {'max_depth': 3, 'min_samples_split': 2}           1.000000   
5  {'max_depth': 3, 'min_samples_split': 3}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.703704           0.666667           0.666667           0.666667   
1           0.703704           0.666667           0.666667           0.666667   
2           0.962963           0.962963           0.888889           0.925926   
3           0.962963           0.962963           0.888889           0.925926   
4           0.962963           0.962963           0.851852           1.000000   
5           0.962963           0.962963           0.851852           1.000000   

   mean_test_score  std_test_score  rank_test_score  
0         0.681481        0.018144                5  
1         0.681481        0.018144                5  
2         0.948148        0.037771                3  
3         0.948148        0.037771                3  
4         0.955556        0.054433                1  
5         0.955556        0.054433                1

In [113]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
items = ['phone','TV','PC','TV','TV','phone','PC','PC']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(encoder.classes_)
print(labels)
print(encoder.inverse_transform(labels))
labels = labels.reshape(-1,1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels) #return sparse matrix
print(oh_labels.toarray())


['PC' 'TV' 'phone']
[2 1 0 1 1 2 0 0]
['phone' 'TV' 'PC' 'TV' 'TV' 'phone' 'PC' 'PC']
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [117]:
item_df = pd.DataFrame(items,columns=['item'])
pd.get_dummies(item_df)

item_PC  item_TV  item_phone
0        0        0           1
1        0        1           0
2        1        0           0
3        0        1           0
4        0        1           0
5        0        0           1
6        1        0           0
7        1        0           0

In [118]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data,columns=iris.feature_names)
print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [119]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(iris_scaled,columns=iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [121]:
from sklearn.preprocessing import MinMaxScaler

scaler  = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.min())
print(iris_df_scaled.max())
print(iris_df_scaled.var())

sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64
