In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array shape:',array1.shape)

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:',type(array2))
print('array2 array shape:',array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array shape:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array shape: (1, 3)


In [3]:
print('array1:{:7}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:      1차원, array2:2차원, array3: 2차원


In [4]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2=[1,2,'test'] #1 2 가 '1' '2' 로 변환
array2=np.array(list2)
print(array2, array2.dtype)
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype) 

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
array_int = np.array([1,2,3])
array_float=array_int.astype('float64')  #= .astype(float)
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array=np.zeros((3,2),dtype='int32')  # dtype=str  비어있는 문자열
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))  # dtype=str  비어있는 문자열
print(one_array) #default dtype = 'float64'
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(2,5)
print(array2)
array3=array2.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1=np.arange(16)
print(array1)
array2=array1.reshape(2,-1)
print(array2)
array3=array2.reshape(8,-1)
print(array3)
array4=array3.reshape(-1,)  # 1차원 변환
print(array4)
array5=array4.reshape(1,-1) #2차원 변환
print(array5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [11]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d)
print('array3d:\n',array3d.tolist()) #리스트로 보기편하게

array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist()) #(8,1) 2차원으로 reshape
print('array5.shape:',array5.shape)

print(array1.shape)
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6.shape:',array6.shape)


array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5.shape: (8, 1)
(8,)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape: (8, 1)


In [12]:
array1=np.arange(start=1, stop=10) #시작 끝 설정
print('array1:',array1)  
value=array1[2]  # =3
print(value,type(value))
print('맨 뒤의 값:',array1[-1])

array1: [1 2 3 4 5 6 7 8 9]
3 <class 'numpy.int32'>
맨 뒤의 값: 9


In [13]:
array1[0]=9  #수정 가능
print(array1)

[9 2 3 4 5 6 7 8 9]


In [14]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)
print('(row=0,col=0) index 가리키는 값:',array2d[0,0])
print('(row=0,col=1) index 가리키는 값:',array2d[0,1])
print('(row=1,col=0) index 가리키는 값:',array2d[1,0])
print('(row=2,col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [15]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]  # array1[0 ~ 2]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
array1=np.arange(start=1,stop=10) #Slicing method
print(array1)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[0:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [18]:
print(array2d[0]) #뒤에오는 인덱스를 없애면 1차원이 된다.
print(array2d[0,:]) #same
print(array2d[1])

[1 2 3]
[1 2 3]
[4 5 6]


In [19]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
array3=array2d[[0,1],2]   # [0,1] 팬시 인덱싱
print('array2d[[0,1],2]=>',array3.tolist())
array4=array2d[[0,2],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())
array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [7, 8]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [20]:
#Boolean Index !
array1d=np.arange(start=1,stop=10)
array3d=array1d[array1d>5]  # 인덱스에 Boolean return식 입력
print(array3d)

[6 7 8 9]


In [21]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [22]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [23]:
#np.sort() ndarray.sort() np.argsort()    DEFAULT='ASCENDING'
org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)
sort_array1=np.sort(org_array)
print('np.sort()로 반환한 행렬:',sort_array1)
print('np.sort()호출 후 원본 행렬:',org_array)
sort_array2=org_array.sort()
print('org_array.sort()로 반환된 정렬행렬:',sort_array2)
print('org_array.sort()호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort()로 반환한 행렬: [1 3 5 9]
np.sort()호출 후 원본 행렬: [3 1 9 5]
org_array.sort()로 반환된 정렬행렬: None
org_array.sort()호출 후 원본 행렬: [1 3 5 9]


In [24]:
sort_array1_desc = np.sort(org_array)[::-1] #역순으로
print("내림차순으로 정렬:",sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [25]:
#2차원 행렬의 정렬
array1d=np.array([8,12,7,1])
array2d=array1d.reshape(2,2)
print(array2d)
sort_array2d_axis0=np.sort(array2d,axis=0)
print('axis0 정렬:\n',sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print('axis1 정렬:\n',sort_array2d_axis1)

[[ 8 12]
 [ 7  1]]
axis0 정렬:
 [[ 7  1]
 [ 8 12]]
axis1 정렬:
 [[ 8 12]
 [ 1  7]]


In [26]:
#np.argsort() 원본 행렬의 원소에 대한 인덱스를 반환
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)  #원본 행렬은 변하지 않는다
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [27]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)[::-1]
print(type(sort_indices))
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [28]:
#np.argsort 사용 예시
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])   #각각 대응되는 점수
# 시험 성적 순으로 학생 이름을 출력하고자 한다.
highindex=np.argsort(score_array)[::-1]
name_array[highindex]


array(['Kate', 'Mike', 'Samuel', 'Sarah', 'John'], dtype='<U6')

In [29]:
#행렬 내적 (행렬곱)
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print("행렬 내적 결과:\n",dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [30]:
#전치 행렬
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [31]:
#Pandas
import pandas as pd
titanic_df=pd.read_csv("data/train.csv") #read_csv ,로 구분한 데이터 read_table tab으로 구분
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [32]:
print(type(titanic_df))
titanic_df

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [33]:
titanic_df.shape

(891, 12)

In [34]:
titanic_df.info() #메타데이터

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [35]:
titanic_df.describe() 

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [36]:
titanic_pclass=titanic_df['Pclass']  #DataFrame['column name'] - return Series type
print(type(titanic_pclass))            #Series,DataFrame be have 'INDEX'
titanic_pclass

<class 'pandas.core.series.Series'>


0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [37]:
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)  #해당 column값의 유형과 건수를 반환, Series 객체에서만 정의

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [38]:
col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1.shape',array1.shape)

df_list1=pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n',df_list1)
df_array1=pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray 만든 DataFrame:\n',df_array1)

array1.shape (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray 만든 DataFrame:
    col1
0     1
1     2
2     3


In [39]:
col_name1=['col1','col2','col3']
list1=[[1,2,3],[11,12,13]]
array1=np.array(list1)
print('array1.shape',array1.shape)

df_list1=pd.DataFrame(list1,columns=col_name1)
print('2차원 리스트로 만든 DataFrame:\n',df_list1)
df_array1=pd.DataFrame(array1,columns=col_name1)
print('2차원 ndarray 만든 DataFrame:\n',df_array1)

array1.shape (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [40]:
#dictionairy to DataFrame
#Key는 문자열 칼럼명으로 매핑, Value는 리스트 or ndarray 칼럼 데이터로 매핑
dictionairy={'col':[1,11],'col2':[2,22],'col3':np.array([3,33])}
df_dict=pd.DataFrame(dictionairy)
print("dictionairy to DataFrame:\n",df_dict)

dictionairy to DataFrame:
    col  col2  col3
0    1     2     3
1   11    22    33


In [41]:
#DataFrame to ndarray : df_abc.values
array3=df_dict.values
print('df_dict.values 타입:',type(array3),'df_dict.values shape:',array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [42]:
#DataFrame to List
list3=df_dict.values.tolist()
print(type(list3))
print(list3)

#DataFrame to dict
dict3=df_dict.to_dict('list')
print('\n',type(dict3))
print(dict3)

<class 'list'>
[[1, 2, 3], [11, 22, 33]]

 <class 'dict'>
{'col': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [43]:
titanic_df['Age_0']=0 #상숫값 할당시 모든 데이터 세트에 일괄 적용
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [44]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1 #쉽게 가공 가능
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [45]:
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100 #업데이트도 쉽게 가능
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   

   Family_No  
0          2  
1          2  
2          1

In [46]:
#DataFrame.drop()    labels (첫번째 매개변수)에 할당되는 값을 axis방향으로 찾는다.
titanic_drop_df=titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      320.0          2  
1      0          PC 17599  71.2833   C85        C      480.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0          1

In [47]:
titanic_df.head(3) # inplace = False - Default

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   

   Family_No  
0          2  
1          2  
2          1

In [48]:
drop_result=titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True) #list형식으로 삭제
print(drop_result) #No return
titanic_df.head(3)

None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [49]:
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('### before axis 0 drop ####')
print(titanic_df.head(3))
titanic_df.drop([0,1,2],axis=0,inplace=True)
print('#### after axis 0 drop ####')
print(titanic_df.head(3))

### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [50]:
#index 객체 추출
titanic_df=pd.read_csv('data/train.csv')
indexes=titanic_df.index
print(indexes)
#index 객체를 실제 array로 변환
print('index 객체 array 값:\n',indexes.values[:100]) #1차원 array

RangeIndex(start=0, stop=891, step=1)
index 객체 array 값:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [51]:
print(type(indexes))
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [52]:
indexes[0]=5 #변경 불가

TypeError: Index does not support mutable operations

In [53]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:',series_fair.max()) #max sum 사용 가능
print('Fair Series sum 값:',series_fair.sum())
print('sum() Fair Series:',sum(series_fair))
print('Fare Seires + 3:\n',(series_fair+3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fare Seires + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [54]:
titanic_reset_df =titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [55]:
titanic_drop=titanic_df.drop([0,1,2,3,4,5,6],axis=0) #.reset_index
titanic_drop.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
7            8         0       3  Palsson, Ma...    male   2.0      3      1  349909  21.0750   NaN        S
8            9         1       3  Johnson, Mr...  female  27.0      0      2  347742  11.1333   NaN        S
9           10         1       2  Nasser, Mrs...  female  14.0      1      0  237736  30.0708   NaN        C

In [56]:
titanic_drop.reset_index(inplace=True)
titanic_drop.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
0      7            8         0       3  Palsson, Ma...    male   2.0      3      1  349909  21.0750   NaN        S
1      8            9         1       3  Johnson, Mr...  female  27.0      0      2  347742  11.1333   NaN        S
2      9           10         1       2  Nasser, Mrs...  female  14.0      1      0  237736  30.0708   NaN        C

In [57]:
#Column = 1  : Series 
print('###before reset_index###')
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts)) #index 제외 column이 1개다 = Series
new_value_counts=value_counts.reset_index(inplace=False,drop=False)  #drop=True 기존 index dropping
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts)) # column이 2개 = DataFrame

###before reset_index###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


In [58]:
#DataFrame 에서 []는 칼럼만 지정 가능한 연산자
print('단일 칼럼 데이터 추출:\n',titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n',titanic_df[['Survived','Pclass']].head(3))
#titanic_df[0] - ERROR

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


In [59]:
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [60]:
#Boolean Indexing - IMPORTANT!
titanic_df[titanic_df['Pclass']==3].head(3) #Plcass가 3인 row들 

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

In [61]:
titanic_head=titanic_df.head(3)  #head를 이용한 Slicing
titanic_head

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [62]:
print('칼럼 위치 기반 인덱싱 데이터 추출:',titanic_df.ix[0,2])
print('칼럼 명 기반 인덱싱 데이터 추출:',titanic_df.ix[0,'Pclass'])

칼럼 위치 기반 인덱싱 데이터 추출: 3
칼럼 명 기반 인덱싱 데이터 추출: 3


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Anaconda\lib\site-packages\pandas\core\indexing.py:961: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  return getattr(section, self.name)[new_key]
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


In [63]:
data={'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
      'Year':[2011,2016,2015,2015],
      'Gender':['Male','Female','Male','Male']}
data_df=pd.DataFrame(data,index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [64]:
print(data_df.ix[0,0])
print(data_df.ix['one',0])
print(data_df.ix[0:2,0:2])
print(data_df.ix[0:3,[0,2]])
print(data_df.ix[:,:])  #Same as data_df.ix[:] 
print('\n',data_df.ix[0]) #인자가 1개면 행  인덱싱
print(data_df.ix[data_df.Year>=2014]) #Year 칼럼 값이 2014보다 크거나 같은 row반환


Chulmin
Chulmin
         Name  Year
one   Chulmin  2011
two  Eunkyung  2016
           Name  Gender
one     Chulmin    Male
two    Eunkyung  Female
three  Jinwoong    Male
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

 Name      Chulmin
Year         2011
Gender       Male
Name: one, dtype: object
           Name  Year  Gender
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until
C:\A

In [65]:
data_df_reset=data_df.reset_index()
data_df_reset=data_df_reset.rename(columns={'index':'old_index'}) #.rename(columns={'A':'B'}) A to B
data_df_reset

old_index      Name  Year  Gender
0       one   Chulmin  2011    Male
1       two  Eunkyung  2016  Female
2     three  Jinwoong  2015    Male
3      four   Soobeom  2015    Male

In [66]:
data_df_reset.index=data_df_reset.index+1
data_df_reset

old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [67]:
data_df_reset.ix[1,1]  # data_df_reset,ix[0,1] : Error 인덱스는 위치기반이 아닌 명칭기반 인덱싱

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


'Chulmin'

In [68]:
#iloc[] - 위치 기반 인덱싱
print(data_df.iloc[0,0])
#data_df.iloc[0,'Name']  - Error
print(data_df)
print(data_df_reset.iloc[0,1])
data_df_reset

Chulmin
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male
Chulmin


old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [69]:
#loc[] - 명칭 기반 인덱싱
data_df.loc['one','Name']

'Chulmin'

In [70]:
data_df_reset.loc[1,'Name'] # 1이 정수형이지만 위치 기반이 아닌 명칭기반 인덱싱

'Chulmin'

In [71]:
print('명칭 기반 ix slicing\n',data_df.ix['one':'two','Name'],'\n')
print('위치 기반 iloc slicing\n',data_df.iloc[0:1,0],'\n')
print('명칭 기반 loc slicing\n',data_df.loc['one':'two','Name'],'\n') #명칭기반은  숫자형이 아닐수 있기
                                                                     #때문에, 최댓값 -1 X

명칭 기반 ix slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object 

위치 기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object 

명칭 기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object 



C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [72]:
#Boolean Indexing - IMPORTANT!
titanic_df=pd.read_csv('data/train.csv')
titanic_boolean=titanic_df[titanic_df['Age']>60] #titanic_df['Age']>60  True or False Series
print(type(titanic_boolean))
titanic_boolean.head()

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked
33            34         0       2  Wheadon, Mr...  male  66.0      0      0  C.A. 24579  10.5000   NaN        S
54            55         0       1  Ostby, Mr. ...  male  65.0      0      1      113509  61.9792   B30        C
96            97         0       1  Goldschmidt...  male  71.0      0      0    PC 17754  34.6542    A5        C
116          117         0       3  Connors, Mr...  male  70.5      0      0      370369   7.7500   NaN        Q
170          171         0       1  Van der hoe...  male  61.0      0      0      111240  33.5000   B19        S

In [73]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head() #60세 이상인 새로운 DataFrame에서 2column 추출

Name   Age
33   Wheadon, Mr...  66.0
54   Ostby, Mr. ...  65.0
96   Goldschmidt...  71.0
116  Connors, Mr...  70.5
170  Van der hoe...  61.0

In [74]:
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head()

Name   Age
33   Wheadon, Mr...  66.0
54   Ostby, Mr. ...  65.0
96   Goldschmidt...  71.0
116  Connors, Mr...  70.5
170  Van der hoe...  61.0

In [75]:
#나이가 60 이상  ,  선실 등급 1등급, 여성 승객 추출
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [76]:
cond1=titanic_df['Age']>60
cond2=titanic_df['Pclass']==1
cond3=titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [79]:
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [83]:
titanic_sorted=titanic_df.sort_values(by=['Pclass','Name'],ascending=True)
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name     Sex    Age  SibSp  Parch  Ticket      Fare    Cabin Embarked
730          731         1       1  Allen, Miss...  female  29.00      0      0   24160  211.3375       B5        S
305          306         1       1  Allison, Ma...    male   0.92      1      2  113781  151.5500  C22 C26        S
297          298         0       1  Allison, Mi...  female   2.00      1      2  113781  151.5500  C22 C26        S

In [84]:
titanic_df.count() #DataFrame에 바로 사용할 경우 모든 칼럼에 결과를 반환

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [85]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [95]:
titanic_groupby=titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [94]:
titanic_groupby=titanic_df.groupby('Pclass').count() #groupby 'col name'   #0 or not   count
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [105]:
titanic_groupby=titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby


PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [109]:
titanic_df.groupby('Pclass')['Age'].agg(['max','min'])  #나이 최대 최저 

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [113]:
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [115]:
titanic_df.isna().head(3)  #isna()  DataFrame에서 True False 값으로 NULL을 찾아준다.

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [116]:
titanic_df.isna().sum()  # 열별 결손 데이터의 총 갯수

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [118]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [120]:
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'].fillna('S',inplace=True)
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [121]:
a=[1,2,3]
square=map(lambda x:x**2,a)
list(square)

[1, 4, 9]

In [122]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name','Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [123]:
titanic_df['Child_Adult2']=titanic_df['Age']*2  #can multiply

In [125]:
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x:'Child' if x<=15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

Age Child_Adult
0     22.00       Adult
1     38.00       Adult
2     26.00       Adult
3     35.00       Adult
4     35.00       Adult
5  21205.17       Adult
6     54.00       Adult
7      2.00       Child

In [126]:
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:'Child' if x<=15 \
                                              else('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      609
Elderly    199
Child       83
Name: Age_cat, dtype: int64

In [128]:
def get_category(age):
    cat='' #공백 문자열
    if age<=5: cat='Baby'
    elif age<=12:cat='Child'
    elif age<=18:cat='Teenager'
    elif age<=25:cat='Student'
    elif age<=35:cat='Young Adult'
    elif age<=60:cat='Adult'
    else: cat='Elderly'
    return cat

titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:get_category(x))
titanic_df['Age_cat'].value_counts()
        

Elderly        199
Young Adult    196
Adult          195
Student        162
Teenager        70
Baby            44
Child           25
Name: Age_cat, dtype: int64