In [2]:
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X_tata=np.array(x_raw,dtype=np.float32)
y_tata=np.array(y_raw,dtype=np.float32)
nb_classes=3

tf.model=tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4,units=nb_classes,use_bias=True))
#Defualt use_vias ==True
tf.model.add(tf.keras.layers.Activation('softmax'))

tf.model.compile(loss='categorical_crossentropy',optimizer=tf.keras.optimizers.SGD(lr=0.1),metrics=['accuracy'])

In [23]:
print('---------------------------------')
a=tf.model.predict(np.array([[1,11,7,9]]))
print(a,tf.keras.backend.eval(tf.argmax(a,axis=1)))
#tf.keras.backend.eval(tf.argmax(a,axis=1)) 
#tf.argmax doesn't return ndarray
print('---------------------------------')
b = tf.model.predict(np.array([[3, -1,0 , 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))
print('---------------------------------')
c=tf.model.predict(np.array([[1,1,0,1]]))
c_onehot=tf.model.predict_classes(np.array([[1,1,0,1]]))
print(c,c_onehot)
print('---------------------------------')
all = tf.model.predict(np.array([[1,11,7,9],[1,3,4,3],[1,1,0,1]]))
all_onehot=tf.model.predict_classes(np.array([[1,11,7,9],[1,3,4,3],[1,1,0,1]]))
print(all,all_onehot)
#tf.model.predict() - like predict_proba because of activation function softmax 
#tf.model.predict_classes = return class ==make ont hot and choose 1
#tf.keras.backend.eval(tf.argmax(b,axis=1)) = same as upper one

---------------------------------
[[2.8174200e-06 9.9998355e-01 1.3686472e-05]] [1]
---------------------------------
[[0.06285075 0.27156654 0.66558266]] [2]
---------------------------------
[[0.13656768 0.589299   0.27413324]] [1]
---------------------------------
[[2.8174200e-06 9.9998355e-01 1.3686472e-05]
 [1.0627013e-02 9.8777652e-01 1.5965301e-03]
 [1.3656768e-01 5.8929902e-01 2.7413324e-01]] [1 1 1]


In [15]:
type(tf.argmax(a,axis=1,name='tensor!'))
# tf.Tensor  [1]


tensorflow.python.framework.ops.EagerTensor