In [2]:
import pandas as pd
import numpy as np


In [203]:
a=pd.read_csv('txt_info.txt',header=None)

In [204]:
c=['0','1','2','3','4','5']
d=a.iloc[c].values

In [205]:
d

array([['전쟁 강제규 장동건 원빈'],
       ['액션 로맨스 멜로 볼프강페터슨 브래드피트 올랜도블룸'],
       ['로맨스 멜로 드라마 이재한 정우성 손예진'],
       ['코미디 판타지 공포 김상진 차승원 장서희'],
       ['액션 스릴러 SF 어드벤처 드라마 롤랜드에머리히 데니스퀘이드 제이크질렌할'],
       ['드라마 안권태 원빈 신하균 김해숙']], dtype=object)

In [206]:
e=(' ').join(d.squeeze())

In [207]:
from sklearn.feature_extraction.text import CountVectorizer

In [208]:
cv=CountVectorizer()

In [209]:
a.loc[850]=e

In [210]:
a

0
0                                        전쟁 강제규 장동건 원빈
1                         액션 로맨스 멜로 볼프강페터슨 브래드피트 올랜도블룸
2                               로맨스 멜로 드라마 이재한 정우성 손예진
3                               코미디 판타지 공포 김상진 차승원 장서희
4             액션 스릴러 SF 어드벤처 드라마 롤랜드에머리히 데니스퀘이드 제이크질렌할
..                                                 ...
846                                     다큐멘터리 와드알-카팁 X
847                                  애니메이션 변희선 조경이 김서영
848                   액션 어드벤처 애니메이션 왕치 김기두 서반석 이다은 박성영
849                       드라마 페르난도메이렐레스 조나단프라이스 안소니홉킨스
850  전쟁 강제규 장동건 원빈 액션 로맨스 멜로 볼프강페터슨 브래드피트 올랜도블룸 로맨스...

[851 rows x 1 columns]

In [211]:
a.values.squeeze()

array(['전쟁 강제규 장동건 원빈', '액션 로맨스 멜로 볼프강페터슨 브래드피트 올랜도블룸',
       '로맨스 멜로 드라마 이재한 정우성 손예진', '코미디 판타지 공포 김상진 차승원 장서희',
       '액션 스릴러 SF 어드벤처 드라마 롤랜드에머리히 데니스퀘이드 제이크질렌할', '드라마 안권태 원빈 신하균 김해숙',
       '판타지 어드벤처 알폰소쿠아론 다니엘래드클리프 엠마왓슨 루퍼트그린트',
       '코미디 어드벤처 애니메이션 앤드류아담슨 마이크마이어스 에디머피 카메론디아즈',
       '스릴러 전쟁 강우석 설경구 안성기 허준호 정재영', '액션 스릴러 SF 샘레이미 토비맥과이어 커스틴던스트',
       '액션 드라마 양윤호 양동근', '로맨스 멜로 뮤지컬 조엘슈마허 제라드버틀러 에미로섬 패트릭윌슨',
       '코미디 로맨스 멜로 곽재용 전지현 장혁', '로맨스 멜로 액션 김태균 조한선 강동원 이청아',
       '드라마 이정철 수애 주현 박지빈', '코미디 공포 신정원 임창정 권오중 임은경 변희봉',
       '액션 미스터리 스릴러 SF 알렉스프로야스 윌스미스', '코미디 로맨스 멜로 권종관 김선아',
       '공포 전쟁 공수창 감우성', '로맨스 멜로 스릴러 변혁 한석규 이은주', '드라마 장예모 유덕화 금성무 장쯔이',
       '코미디 로맨스 멜로 비반키드론 르네젤위거 휴그랜트 콜린퍼스', '코미디 로맨스 멜로 김호준 김래원 문근영',
       '코미디 로맨스 멜로 스티븐스필버그 톰행크스 캐서린제타존스',
       '애니메이션 판타지 로맨스 멜로 미야자키하야오 바이쇼치에코 기무라타쿠야',
       '스릴러 판타지 에릭브레스 애쉬튼커처 멜로라월터스 에이미스마트', '드라마 송해성 설경구',
       '범죄 스릴러 최동훈 박신양 백윤식 염정아', '액션 판타지 스티븐소머즈 휴잭맨 케이트베킨세일',
       '판타지 로맨스 멜로 코미디 드라마 길정거 제니퍼러브휴이트 폴니콜스', '코

In [212]:
cv_a=cv.fit_transform(a.values.squeeze())

In [213]:
cv_a.toarray().shape

(851, 1666)

In [214]:
from sklearn.metrics.pairwise import cosine_similarity
cs=cosine_similarity(cv_a,cv_a)

In [215]:
cs.shape

(851, 851)

In [216]:
len(c)

6

In [254]:
c

['0', '1', '2', '3', '4', '5']

In [255]:
k=list(map(int,c))

In [262]:
k

[0, 1]

In [257]:
d

array([0, 1, 2, 3, 4, 5])

In [268]:
for x in k:
    new_d=np.delete(new_d,np.where(d==x))
new_d

array([0, 2, 3, 4, 5])

In [273]:
new_d=np.delete(d,np.where(d==1))

In [249]:
np.where(d==1)

(array([1], dtype=int64),)

In [277]:
indexes=np.argsort(cs[850])[::-1]

In [279]:
indexes[:20]

array([850,   2,   4,   1,   5,  29,  43, 777,  49, 301, 403, 131, 139,
       430, 240, 140, 175, 834,  58, 789], dtype=int64)

In [280]:
g=list(map(int,c))

In [282]:
for x in g:
    indexes=np.delete(indexes,np.where(indexes==x))
indexes[:20]

array([850,  29,  43, 777,  49, 301, 403, 131, 139, 430, 240, 140, 175,
       834,  58, 789, 662, 359, 231, 256], dtype=int64)

In [231]:
d=list(map(int,c))
d

[0, 1, 2, 3, 4, 5]

In [290]:
new_df = f.loc[np.argsort(cs[850])[::-1][len(c)+1:len(c)+15]].sort_values(by='movie_rating',
                                                                                ascending=False)[:10]

In [299]:
type(np.argsort(cs[850])[::-1][:20][0:5])

numpy.ndarray

In [315]:
 indexes=np.delete(indexes,np.where(indexes==850))

In [316]:
new_df=f.loc[indexes[:20]].sort_values(by='movie_rating',ascending=False)[:10]
new_df

Unnamed: 0     movie_name  movie_rating  \
301         301            아저씨           9.2   
834         834      피아니스트의 전설           9.1   
29           29          이프 온리           8.8   
49           49      꽃피는 봄이 오면           8.8   
139         139         오만과 편견           8.7   
359         359          리얼 스틸           8.7   
58           58  미스터 & 미세스 스미스           8.5   
662         662            강철비           8.5   
403         403           늑대소년           8.4   
256         256         7급 공무원           8.4   

                            movie_genre movie_director  \
301                       ['액션', '드라마']            이정범   
834                ['드라마', '로맨스', '멜로']      쥬세페 토르나토레   
29   ['판타지', '로맨스', '멜로', '코미디', '드라마']           길 정거   
49                 ['로맨스', '멜로', '드라마']            류장하   
139                ['로맨스', '멜로', '드라마']          조 라이트   
359                 ['액션', '드라마', 'SF']           숀 레비   
58                  ['액션', '로맨스', '멜로']         더그 라이만   
662                       ['액션', '드라마']            양우석   
403         ['로맨스', '멜로', '드라마', '판타지']            조성희   
256          ['코미디', '로맨스', '멜로', '액션']            신태라   

                 movie_actor   movie_genre_split movie_director_split  \
301            ['원빈', '김새론']              액션 드라마                  이정범   
834    ['팀 로스', '프룻 테일러 빈스']          드라마 로맨스 멜로             쥬세페토르나토레   
29   ['제니퍼 러브 휴이트', '폴 니콜스']  판타지 로맨스 멜로 코미디 드라마                  길정거   
49                   ['최민식']          로맨스 멜로 드라마                  류장하   
139   ['키이라 나이틀리', '매튜 맥퍼딘']          로맨스 멜로 드라마                 조라이트   
359                 ['휴 잭맨']           액션 드라마 SF                  숀레비   
58     ['브래드 피트', '안젤리나 졸리']           액션 로맨스 멜로                더그라이만   
662           ['정우성', '곽도원']              액션 드라마                  양우석   
403           ['송중기', '박보영']      로맨스 멜로 드라마 판타지                  조성희   
256           ['김하늘', '강지환']       코미디 로맨스 멜로 액션                  신태라   

    movie_actor_split  
301            원빈 김새론  
834       팀로스 프룻테일러빈스  
29      제니퍼러브휴이트 폴니콜스  
49                최민식  
139     키이라나이틀리 매튜맥퍼딘  
359               휴잭맨  
58       브래드피트 안젤리나졸리  
662           정우성 곽도원  
403           송중기 박보영  
256           김하늘 강지환

In [308]:
new_df = f.loc[np.argsort(cs[850])[::-1][len(c)+1:len(c)+
                                         15]].sort_values(by='movie_rating',ascending=False)[:10]

In [312]:
new_df = f.loc[np.argsort(cs[850])[::-1][9:15]].sort_values(by='movie_rating',ascending=False)[:10]

In [313]:
np.argsort(cs[850])[::-1][0]

850

In [306]:
new_df2 = f.loc[np.argsort(cs[850])[::-1][:10]].sort_values(by='movie_rating',ascending=False)[:10]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [291]:
new_df

Unnamed: 0      movie_name  movie_rating  \
301         301             아저씨           9.2   
834         834       피아니스트의 전설           9.1   
49           49       꽃피는 봄이 오면           8.8   
139         139          오만과 편견           8.7   
58           58   미스터 & 미세스 스미스           8.5   
662         662             강철비           8.5   
403         403            늑대소년           8.4   
777         777      알리타: 배틀 엔젤           8.3   
430         430             반창꼬           8.3   
240         240  스텝업 2 : 더 스트리트           8.3   

                                  movie_genre movie_director  \
301                             ['액션', '드라마']            이정범   
834                      ['드라마', '로맨스', '멜로']      쥬세페 토르나토레   
49                       ['로맨스', '멜로', '드라마']            류장하   
139                      ['로맨스', '멜로', '드라마']          조 라이트   
58                        ['액션', '로맨스', '멜로']         더그 라이만   
662                             ['액션', '드라마']            양우석   
403               ['로맨스', '멜로', '드라마', '판타지']            조성희   
777  ['액션', '어드벤처', '로맨스', '멜로', '스릴러', 'SF']      로버트 로드리게즈   
430                      ['드라마', '로맨스', '멜로']            정기훈   
240                      ['드라마', '로맨스', '멜로']            존 추   

                 movie_actor      movie_genre_split movie_director_split  \
301            ['원빈', '김새론']                 액션 드라마                  이정범   
834    ['팀 로스', '프룻 테일러 빈스']             드라마 로맨스 멜로             쥬세페토르나토레   
49                   ['최민식']             로맨스 멜로 드라마                  류장하   
139   ['키이라 나이틀리', '매튜 맥퍼딘']             로맨스 멜로 드라마                 조라이트   
58     ['브래드 피트', '안젤리나 졸리']              액션 로맨스 멜로                더그라이만   
662           ['정우성', '곽도원']                 액션 드라마                  양우석   
403           ['송중기', '박보영']         로맨스 멜로 드라마 판타지                  조성희   
777              ['로사 살라자르']  액션 어드벤처 로맨스 멜로 스릴러 SF             로버트로드리게즈   
430            ['고수', '한효주']             드라마 로맨스 멜로                  정기훈   
240  ['브리아나 에비건', '로버트 호프먼']             드라마 로맨스 멜로                   존추   

    movie_actor_split  
301            원빈 김새론  
834       팀로스 프룻테일러빈스  
49                최민식  
139     키이라나이틀리 매튜맥퍼딘  
58       브래드피트 안젤리나졸리  
662           정우성 곽도원  
403           송중기 박보영  
777            로사살라자르  
430            고수 한효주  
240    브리아나에비건 로버트호프먼

In [233]:
np.argsort(cs[850])[::-1]

array([850,   2,   4,   1,   5,  29,  43, 777,  49, 301, 403, 131, 139,
       430, 240, 140, 175, 834,  58, 789, 662, 359, 231, 256,  85, 120,
       460, 492, 666, 418,  10, 530, 797, 478, 116, 382, 260,  81,   0,
       513, 824, 410, 287, 808,  64, 276,   3,  78, 498, 828,  91,  13,
       364, 299, 495,  50, 466, 455, 303, 327, 249, 229, 448, 363, 550,
       579,  17, 130, 821, 637, 726, 112, 538, 791, 708, 810, 431,  36,
       760, 429, 417, 756,  86, 340,  80,  38,  75,  34,  22,  67, 122,
       551, 138, 245, 168,  12, 793, 285, 500, 191, 786, 114, 321,  19,
       187,  23,  65,  70, 148,  79, 441, 770, 626, 127, 580,  56,  71,
       408, 683, 383, 211, 454, 470, 581, 811,  21, 248, 328,  24, 149,
       465, 322, 397, 427, 482, 190, 324, 277, 743, 758, 464, 147, 768,
       724,  96, 336, 678, 540, 292, 297, 790, 126, 304,  59, 524, 816,
       162,  63, 519, 129, 514, 219, 432, 237, 504, 172, 283, 490,  87,
       267, 608,  47, 387, 658, 270, 209, 655, 653, 106, 487, 53

In [288]:
f.loc[np.argsort(cs[850])[::-1]].sort_values(by='movie_rating',ascending=False)

SyntaxError: invalid syntax (<ipython-input-288-2f9479965923>, line 1)

In [286]:
f.loc[indexes]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [157]:
index_2020=np.argsort(cs[850])[::-1][len(c)+1:]
f.loc[index_2020[index_2020>800]]

Unnamed: 0               movie_name  movie_rating  \
834         834                피아니스트의 전설           9.1   
824         824              타오르는 여인의 초상           8.3   
821         821                 포드 V 페라리           8.6   
828         828          21 브릿지: 테러 셧다운            7.5   
810         810                   작은 아씨들           7.6   
843         843              고흐, 영원의 문에서           8.2   
811         811           미스터 주: 사라진 VIP           5.1   
802         802                      백두산           6.4   
808         808                     미드웨이           7.7   
836         836                 페인 앤 글로리           7.6   
827         827                    조조 래빗           8.4   
816         816                     1917           7.3   
809         809                       시동           7.5   
805         805                      클로젯           7.1   
801         801                      히트맨           6.4   
820         820                      기생충           7.9   
845         845      이 멋진 세계에 축복을! 붉은 전설           7.7   
815         815                스파이 지니어스            8.6   
837         837                       캣츠           5.6   
812         812              나쁜 녀석들: 포에버           6.5   
839         839                   하이, 젝시           7.0   
830         830                   프린스 코기           7.2   
803         803                   닥터 두리틀           6.6   
804         804                   정직한 후보           7.6   
832         832                      젠틀맨           8.1   
840         840     오즈의 마법사: 요술구두와 말하는 책           4.0   
806         806                    해치지않아           6.4   
848         848                   슈퍼 베어            6.6   
825         825                    수퍼 소닉           6.8   
826         826                      인셉션           8.7   
813         813       스타워즈: 라이즈 오브 스카이워커           6.9   
817         817  버즈 오브 프레이(할리 퀸의 황홀한 해방)           6.9   
842         842             극장판 원피스 스탬피드           7.6   
818         818                   겨울왕국 2           7.4   
807         807              천문: 하늘에 묻는다           8.3   
841         841            하이큐!! 땅 VS 하늘           6.9   
847         847      핑크퐁 시네마 콘서트 : 우주대탐험           7.1   
846         846                     사마에게           9.7   
844         844        울지마 톤즈 2 : 슈크란 바바           9.7   
819         819  신비아파트 극장판 하늘도깨비 대 요르문간드           7.8   
822         822                    인비저블맨           7.0   
823         823                  나이브스 아웃           8.1   
829         829       극장판 미니특공대: 공룡왕 디노            7.6   
831         831                   눈의 여왕4           8.0   
833         833                     파바로티           8.7   
814         814         지푸라기라도 잡고 싶은 짐승들           7.0   
835         835           해리포터와 아즈카반의 죄수           8.4   
838         838               타발루가와 얼음공주           5.7   

                                    movie_genre movie_director  \
834                        ['드라마', '로맨스', '멜로']      쥬세페 토르나토레   
824                        ['로맨스', '멜로', '드라마']          셀린 샴마   
821                               ['액션', '드라마']        제임스 맨골드   
828                  ['액션', '범죄', '스릴러', '드라마']        브라이언 커크   
810                        ['드라마', '로맨스', '멜로']         그레타 거윅   
843                                     ['드라마']        줄리안 슈나벨   
811                              ['코미디', '드라마']            김태윤   
802                               ['드라마', '액션']            이해준   
808                         ['액션', '드라마', '전쟁']       롤랜드 에머리히   
836                                     ['드라마']      페드로 알모도바르   
827                        ['코미디', '드라마', '전쟁']       타이카 와이티티   
816                               ['전쟁', '드라마']          샘 멘데스   
809                                     ['드라마']            최정열   
805                             ['미스터리', '드라마']            김광빈   
801                               ['코미디', '액션']            최원섭   
820                                     ['드라마']            봉준호   
845               ['애니메이션', '액션', '코미디',

In [159]:
m=pd.read_csv('movie_df.csv')
m

Unnamed: 0           movie_name  movie_rating  \
0             0             태극기 휘날리며           9.1   
1             1                  트로이           8.4   
2             2          내 머리 속의 지우개           8.7   
3             3               귀신이 산다           6.4   
4             4                 투모로우           8.3   
..          ...                  ...           ...   
845         845  이 멋진 세계에 축복을! 붉은 전설           7.7   
846         846                 사마에게           9.7   
847         847  핑크퐁 시네마 콘서트 : 우주대탐험           7.1   
848         848               슈퍼 베어            6.6   
849         849                 두 교황           9.1   

                            movie_genre movie_director  \
0                                ['전쟁']            강제규   
1                   ['액션', '로맨스', '멜로']        볼프강 페터슨   
2                  ['로맨스', '멜로', '드라마']            이재한   
3                  ['코미디', '판타지', '공포']            김상진   
4    ['액션', '스릴러', 'SF', '어드벤처', '드라마']       롤랜드 에머리히   
..                                  ...            ...   
845       ['애니메이션', '액션', '코미디', '판타지']       칸자키 타카오미   
846                           ['다큐멘터리']        와드 알-카팁   
847                           ['애니메이션']            변희선   
848             ['액션', '어드벤처', '애니메이션']             왕치   
849                             ['드라마']     페르난도 메이렐레스   

                                    movie_actor   movie_genre_split  \
0                                 ['장동건', '원빈']                  전쟁   
1                          ['브래드 피트', '올랜도 블룸']           액션 로맨스 멜로   
2                                ['정우성', '손예진']          로맨스 멜로 드라마   
3                                ['차승원', '장서희']          코미디 판타지 공포   
4                        ['데니스 퀘이드', '제이크 질렌할']  액션 스릴러 SF 어드벤처 드라마   
..                                          ...                 ...   
845  ['후쿠시마 쥰', '아마미야 소라', '타카하시 리에', '카야노 아이']    애니메이션 액션 코미디 판타지   
846                                           X               다큐멘터리   
847                              ['조경이', '김서영']               애니메이션   
848                ['김기두', '서반석', '이다은', '박성영']       액션 어드벤처 애니메이션   
849                     ['조나단 프라이스', '안소니 홉킨스']                 드라마   

    movie_director_split          movie_actor_split  
0                    강제규                     장동건 원빈  
1                 볼프강페터슨                브래드피트 올랜도블룸  
2                    이재한                    정우성 손예진  
3                    김상진                    차승원 장서희  
4                롤랜드에머리히              데니스퀘이드 제이크질렌할  
..                   ...                        ...  
845              칸자키타카오미  후쿠시마쥰 아마미야소라 타카하시리에 카야노아이  
846               와드알-카팁                          X  
847                  변희선                    조경이 김서영  
848                   왕치            김기두 서반석 이다은 박성영  
849            페르난도메이렐레스             조나단프라이스 안소니홉킨스  

[850 rows x 9 columns]

In [160]:
l=f.loc[np.argsort(cs[850])[::-1][len(c)+1:len(c)+11]]

In [190]:
l

movie_name  movie_rating   movie_genre_split movie_director_split  \
49        꽃피는 봄이 오면           8.8          로맨스 멜로 드라마                  류장하   
47           돈 텔 파파           6.8             코미디 드라마                  이상훈   
550             베테랑           8.4              액션 드라마                  류승완   
43         말죽거리 잔혹사           7.9       로맨스 멜로 액션 드라마                   유하   
29            이프 온리           8.8  판타지 로맨스 멜로 코미디 드라마                  길정거   
139          오만과 편견           8.7          로맨스 멜로 드라마                 조라이트   
140         게이샤의 추억           6.6          로맨스 멜로 드라마                  롭마셜   
240  스텝업 2 : 더 스트리트           8.3          드라마 로맨스 멜로                   존추   
2       내 머리 속의 지우개           8.7          로맨스 멜로 드라마                  이재한   
175              밀양           8.0          로맨스 멜로 드라마                  이창동   

    movie_actor_split  
49                최민식  
47            정웅인 유승호  
550           황정민 유아인  
43        권상우 이정진 한가인  
29      제니퍼러브휴이트 폴니콜스  
139     키이라나이틀리 매튜맥퍼딘  
140         장쯔이 와타나베켄  
240    브리아나에비건 로버트호프먼  
2             정우성 손예진  
175           송강호 전도연

In [166]:
l=l.drop(['Unnamed: 0','movie_genre','movie_director','movie_actor'],axis=1)

In [176]:
p=l.reset_index(drop=True)

In [180]:
p.index +=1 

In [181]:
p

movie_name  movie_rating   movie_genre_split movie_director_split  \
1        꽃피는 봄이 오면           8.8          로맨스 멜로 드라마                  류장하   
2           돈 텔 파파           6.8             코미디 드라마                  이상훈   
3              베테랑           8.4              액션 드라마                  류승완   
4         말죽거리 잔혹사           7.9       로맨스 멜로 액션 드라마                   유하   
5            이프 온리           8.8  판타지 로맨스 멜로 코미디 드라마                  길정거   
6           오만과 편견           8.7          로맨스 멜로 드라마                 조라이트   
7          게이샤의 추억           6.6          로맨스 멜로 드라마                  롭마셜   
8   스텝업 2 : 더 스트리트           8.3          드라마 로맨스 멜로                   존추   
9      내 머리 속의 지우개           8.7          로맨스 멜로 드라마                  이재한   
10              밀양           8.0          로맨스 멜로 드라마                  이창동   

   movie_actor_split  
1                최민식  
2            정웅인 유승호  
3            황정민 유아인  
4        권상우 이정진 한가인  
5      제니퍼러브휴이트 폴니콜스  
6      키이라나이틀리 매튜맥퍼딘  
7          장쯔이 와타나베켄  
8     브리아나에비건 로버트호프먼  
9            정우성 손예진  
10           송강호 전도연

In [188]:
p=p.rename(columns={'movie_name' : 'MOVIE','movie_rating' : 'Rating','movie_genre_split':'Genre','movie_director_split':'Director','movie_actor_split':'Cast'})


In [189]:
p

MOVIE  Rating               Genre Director            Cast
1        꽃피는 봄이 오면     8.8          로맨스 멜로 드라마      류장하             최민식
2           돈 텔 파파     6.8             코미디 드라마      이상훈         정웅인 유승호
3              베테랑     8.4              액션 드라마      류승완         황정민 유아인
4         말죽거리 잔혹사     7.9       로맨스 멜로 액션 드라마       유하     권상우 이정진 한가인
5            이프 온리     8.8  판타지 로맨스 멜로 코미디 드라마      길정거   제니퍼러브휴이트 폴니콜스
6           오만과 편견     8.7          로맨스 멜로 드라마     조라이트   키이라나이틀리 매튜맥퍼딘
7          게이샤의 추억     6.6          로맨스 멜로 드라마      롭마셜       장쯔이 와타나베켄
8   스텝업 2 : 더 스트리트     8.3          드라마 로맨스 멜로       존추  브리아나에비건 로버트호프먼
9      내 머리 속의 지우개     8.7          로맨스 멜로 드라마      이재한         정우성 손예진
10              밀양     8.0          로맨스 멜로 드라마      이창동         송강호 전도연