In [0]:
import torch

In [0]:
data = torch.arange(1.,11.)
print(data)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [0]:
print(data.size())

torch.Size([10])


In [0]:
import torch.nn as nn

In [0]:
input_size=1
hidden_size=2
num_layers=1

In [0]:
rnn = nn.RNN(
    input_size=input_size,
    hidden_size=hidden_size,
    num_layers=num_layers,
    nonlinearity='tanh',
    batch_first=True,
    bidirectional=False,
)

In [0]:
batch_size = 2
seq_length = 5

In [0]:
inputs = data.view(batch_size,seq_length,1)

In [0]:
print(inputs)
print(inputs.shape)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]])
torch.Size([2, 5, 1])


In [0]:
outputs,h_n = rnn(inputs)

In [0]:
print(outputs)

tensor([[[-0.8808,  0.0748],
         [-0.8359, -0.1789],
         [-0.9282, -0.0597],
         [-0.9530,  0.1282],
         [-0.9698,  0.3630]],

        [[-0.9945,  0.7785],
         [-0.9848,  0.7584],
         [-0.9920,  0.8285],
         [-0.9955,  0.8852],
         [-0.9975,  0.9235]]], grad_fn=<TransposeBackward1>)


In [0]:
print(outputs.shape) #batchsize seq_len  hidden_size*num_direction

torch.Size([2, 5, 2])


In [0]:
print(h_n)
print(h_n.size())# num_layer*num_direction, batch_size,hidden_size

tensor([[[-0.9698,  0.3630],
         [-0.9975,  0.9235]]], grad_fn=<StackBackward>)
torch.Size([1, 2, 2])


In [0]:
rnn = nn.RNN(
    input_size=input_size,
    hidden_size=hidden_size,
    num_layers=3,
    batch_first=True,
)

In [0]:
out,h_n = rnn(inputs)

In [0]:
print(out)
print(out.size())

tensor([[[-0.2359, -0.6121],
         [-0.6809, -0.4029],
         [-0.6851, -0.5317],
         [-0.7448, -0.4984],
         [-0.7368, -0.5180]],

        [[-0.2165, -0.6655],
         [-0.6768, -0.4685],
         [-0.6988, -0.5346],
         [-0.7471, -0.5093],
         [-0.7404, -0.5187]]], grad_fn=<TransposeBackward1>)
torch.Size([2, 5, 2])


In [0]:
print(h_n)
print(h_n.size())

tensor([[[-0.9887,  0.9835],
         [-1.0000,  0.9998]],

        [[ 0.3271, -0.7924],
         [ 0.3159, -0.7962]],

        [[-0.7368, -0.5180],
         [-0.7404, -0.5187]]], grad_fn=<StackBackward>)
torch.Size([3, 2, 2])


In [0]:
rnn = nn.RNN(
    input_size = input_size,
    hidden_size = hidden_size,
    num_layers = num_layers,
    batch_first=True,
    bidirectional=True
)

In [0]:
output,h_n = rnn(inputs)


In [0]:
print(output,output.size())

tensor([[[-0.6402,  0.1881, -0.9675, -0.0502],
         [-0.6854,  0.5516, -0.9906,  0.3258],
         [-0.7388,  0.7656, -0.9974,  0.6146],
         [-0.7684,  0.8774, -0.9993,  0.7962],
         [-0.7845,  0.9343, -0.9998,  0.9127]],

        [[-0.6669,  0.9316, -0.9999,  0.9483],
         [-0.7957,  0.9794, -1.0000,  0.9746],
         [-0.8052,  0.9892, -1.0000,  0.9876],
         [-0.8095,  0.9940, -1.0000,  0.9939],
         [-0.8131,  0.9967, -1.0000,  0.9975]]], grad_fn=<TransposeBackward1>) torch.Size([2, 5, 4])


In [0]:
print(h_n,h_n.size())

tensor([[[-0.7845,  0.9343],
         [-0.8131,  0.9967]],

        [[-0.9675, -0.0502],
         [-0.9999,  0.9483]]], grad_fn=<StackBackward>) torch.Size([2, 2, 2])


In [0]:
output = output.view(batch_size,seq_length,2,hidden_size)

In [0]:
print(output)

tensor([[[[-0.6402,  0.1881],
          [-0.9675, -0.0502]],

         [[-0.6854,  0.5516],
          [-0.9906,  0.3258]],

         [[-0.7388,  0.7656],
          [-0.9974,  0.6146]],

         [[-0.7684,  0.8774],
          [-0.9993,  0.7962]],

         [[-0.7845,  0.9343],
          [-0.9998,  0.9127]]],


        [[[-0.6669,  0.9316],
          [-0.9999,  0.9483]],

         [[-0.7957,  0.9794],
          [-1.0000,  0.9746]],

         [[-0.8052,  0.9892],
          [-1.0000,  0.9876]],

         [[-0.8095,  0.9940],
          [-1.0000,  0.9939]],

         [[-0.8131,  0.9967],
          [-1.0000,  0.9975]]]], grad_fn=<ViewBackward>)


In [0]:
outputs_f = output[:,:,0,:]

In [0]:
outputs_f

tensor([[[-0.6402,  0.1881],
         [-0.6854,  0.5516],
         [-0.7388,  0.7656],
         [-0.7684,  0.8774],
         [-0.7845,  0.9343]],

        [[-0.6669,  0.9316],
         [-0.7957,  0.9794],
         [-0.8052,  0.9892],
         [-0.8095,  0.9940],
         [-0.8131,  0.9967]]], grad_fn=<SliceBackward>)

In [0]:
outputs_b = output[:,:,1,:]
outputs_b

tensor([[[-0.9675, -0.0502],
         [-0.9906,  0.3258],
         [-0.9974,  0.6146],
         [-0.9993,  0.7962],
         [-0.9998,  0.9127]],

        [[-0.9999,  0.9483],
         [-1.0000,  0.9746],
         [-1.0000,  0.9876],
         [-1.0000,  0.9939],
         [-1.0000,  0.9975]]], grad_fn=<SliceBackward>)

In [0]:
h_n_f = h_n[:,0,:,:]
h_n_b = h_n[:,1,:,:]

IndexError: ignored

In [0]:
import torchvision

In [0]:
import torchvision.transforms as transforms

transform = transforms.Compose([
                                transforms.ToTensor()
])
batch_size=64

In [0]:
trainset = torchvision.datasets.MNIST(root='./',train=True,download=True,transform=transform)
testset = torchvision.datasets.MNIST(root='./',train=False,download=True,transform=transform)

Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw


Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw


Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw


Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw
Processing...
Done!





/pytorch/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


In [0]:
from multiprocessing import cpu_count

num_workers = int(cpu_count()/2)
print(num_workers)

1


In [0]:
trainloader = torch.utils.data.DataLoader(trainset,batch_size=batch_size,shuffle=True,num_workers=num_workers)
testloader = torch.utils.data.DataLoader(testset,batch_size=batch_size,shuffle=True,num_workers=num_workers)

In [0]:
input_size = 1
hidden_size = 2
num_layers = 1
batch_size = 2
seq_length = 5

In [0]:
class ImageRNN(nn.Module):
    def __init__(self,batch_size,seq_length,input_size,hidden_size,num_classes,device):
        super().__init__()
        self.batch_size = batch_size
        self.seq_length = seq_length
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_classes = num_classes
        self.device = device
        self.rnn = nn.RNN(self.input_size,self.hidden_size)
        self.fc = nn.Linear(self.hidden_size,self.num_classes)

    def init_hidden(self):
        return torch.zeros(1,self.batch_size,self.hidden_size).to(self.device)

    def forward(self,x):
        x = x.permute(1,0,2)
        self.batch_size = x.size(1)
        self.hidden = self.init_hidden()
        _,self.hidden = self.rnn(self.hidden)
        outputs = self.fc(self.hidden)

        return outputs.view(-1,self.num_classes)

In [0]:
seq_length = 28
input_size = 28
hidden_size = 150
num_classes = 10
epochs = 10


In [0]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


In [0]:
import torch.optim as optim

In [0]:
model = ImageRNN(batch_size,seq_length,input_size,hidden_size,num_classes,device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [0]:
for epoch in range(epochs):
    model.train()
    train_loss = 0
    train_correct = 0

    for x,y in trainloader:
        optimizer.zero_grad()
        model.hidden = model.init_hidden()
        x= x.view(-1,28,28)
        x = x.to(device)
        y = y.to(device)
        outputs = model(x)
        loss = criterion(outputs,y)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
        _, predicted= output.max(1)
        train_correct += predicted.eq(y).sum().item()

    train_loss = train_loss/len(trainloader)
    train_acc = train_correct /len(trainset)

torch.Size([64, 28, 28])


RuntimeError: ignored

In [0]:
input_size =1
hidden_size = 2
num_layers = 2
batch_size= 2
seq_length = 5


In [0]:
lstm = nn.LSTM(
    input_size = input_size,
    hidden_size = hidden_size,
    num_layers = num_layers,
    batch_first = True,
    bidirectional = False
)


In [0]:
data = torch.arange(1.,11.)

In [0]:
inputs = data.view()