In [1]:
import torch

In [2]:
x = torch.rand(2,3)
x

tensor([[0.3989, 0.0818, 0.5270],
        [0.4231, 0.6569, 0.2679]])

In [3]:
type(x)

torch.Tensor

In [4]:
x =  torch.randn(2,3)
x

tensor([[-0.5738,  0.7988,  1.6760],
        [ 1.1030,  1.2086, -0.6622]])

In [5]:
x = torch.randperm(5) # good for index
x

tensor([0, 2, 4, 1, 3])

In [6]:
x = torch.zeros(2,3) # default dtype is float tensor
print(x)
x = torch.ones(2,3)
print(x)
x = torch.arange(0,3,0.5)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])


In [14]:
x = torch.FloatTensor(1,3)
print(x)
print(x.shape)  #  torch.Size[0]  == int

tensor([[ 2.0000e+00,  3.0000e+00, -2.7327e+36]])
torch.Size([1, 3])


In [12]:
type(x.shape[0])

int

In [18]:
x = torch.FloatTensor([[2,3]]) # in list make tensor by inseted value
x.dtype

torch.float32

In [19]:
x = x.type_as(torch.IntTensor())
x.dtype

torch.int32

In [39]:
import numpy as np

x1 = np.ndarray(shape=(2,3),dtype=int,buffer = np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [23]:
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [32]:
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [44]:
x = torch.rand(4,3)
print(x)
out = torch.index_select(x,0,torch.LongTensor([0,3])) # index
out

tensor([[0.9745, 0.1479, 0.4265],
        [0.1755, 0.6137, 0.1071],
        [0.7003, 0.8288, 0.9686],
        [0.1489, 0.7562, 0.7845]])


tensor([[0.9745, 0.1479, 0.4265],
        [0.1489, 0.7562, 0.7845]])

In [50]:
x = torch.randn(2,3)
print(x)
mask = torch.BoolTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)
print(out)

tensor([[ 0.6954, -0.7816, -0.6399],
        [-1.7585,  0.3386, -0.5635]])
tensor([-0.6399,  0.3386])


In [57]:
x = torch.empty(5,3)
print(x) # values that are contained by memory initially

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39]])


In [61]:
x = torch.rand(5,3)
print(x)  # float32  IS DEFAULT !!!!!!!!!

tensor([[0.1281, 0.4922, 0.0630],
        [0.9196, 0.5204, 0.9426],
        [0.8748, 0.5493, 0.9341],
        [0.0612, 0.8138, 0.9241],
        [0.2454, 0.6198, 0.7322]])


In [64]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [75]:
x = torch.tensor([5.5,3])
print(x)
print(x.dtype)

tensor([5.5000, 3.0000])
torch.float32


In [76]:
x = x.new_ones(5,3,dtype=torch.double) # float64
#  vs  x = torch.ones(5,3)   #new_ones() 
#works with existing tensor.
#y will inherit the datatype from x and it will run on same device as defined in x
print(x)
print(x.dtype)
x = torch.randn_like(x,dtype=torch.float)
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.float64
tensor([[-0.6485, -0.0713, -1.2607],
        [ 0.2782, -1.3378,  0.3580],
        [-1.0993,  0.7116, -0.8519],
        [ 0.7495,  2.4575, -0.6683],
        [ 0.0143, -1.6813,  0.7343]])
torch.float32


In [77]:
x.size()

torch.Size([5, 3])

In [78]:
y = torch.rand(5,3)
x+y

tensor([[-0.1256,  0.2275, -1.2081],
        [ 0.4420, -1.1060,  0.3800],
        [-0.3496,  1.4751, -0.6774],
        [ 1.1195,  3.1901, -0.4753],
        [ 0.8995, -1.0736,  1.6241]])

In [80]:
print(torch.add(x,y))

tensor([[-0.1256,  0.2275, -1.2081],
        [ 0.4420, -1.1060,  0.3800],
        [-0.3496,  1.4751, -0.6774],
        [ 1.1195,  3.1901, -0.4753],
        [ 0.8995, -1.0736,  1.6241]])


In [81]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[-0.1256,  0.2275, -1.2081],
        [ 0.4420, -1.1060,  0.3800],
        [-0.3496,  1.4751, -0.6774],
        [ 1.1195,  3.1901, -0.4753],
        [ 0.8995, -1.0736,  1.6241]])

In [82]:
y.add_(x)  # y = y+x

tensor([[-0.1256,  0.2275, -1.2081],
        [ 0.4420, -1.1060,  0.3800],
        [-0.3496,  1.4751, -0.6774],
        [ 1.1195,  3.1901, -0.4753],
        [ 0.8995, -1.0736,  1.6241]])

In [86]:
print(x[:,1])

tensor([-0.0713, -1.3378,  0.7116,  2.4575, -1.6813])


In [87]:
x = torch.randn(4,4)
print(x)
y = x.view(16)   # ndarray.reshape
z = x.view(-1,8)
print(x.size(),y.shape,z.size())

tensor([[ 2.1370,  1.3554, -0.7184,  1.2630],
        [-1.3494,  1.7244,  0.1574,  0.7338],
        [ 0.7190,  0.0660, -1.5777,  0.4650],
        [-0.2436, -1.0917, -1.4115,  0.4271]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [88]:
x = torch.randn(1)
print(x)
print(x.item()) # get 1,1 size tensor value

tensor([-0.0872])
-0.08718699961900711


In [93]:
a = torch.ones(5)
b = a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [95]:
a = np.ones(5)
b = torch.from_numpy(a) # Shallow Copy
np.add(a,1,out=a)
print(a,b)   

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [96]:
c = np.ones(5)
d = torch.tensor(c) # Make new Object   Deep copy
np.add(c,1,out=c)
print(c,d)  

[2. 2. 2. 2. 2.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
