In [1]:
import torch

In [2]:
torch.__version__

'1.4.0'

In [3]:
X = torch.Tensor(2,3) # random number in 2,3 size Tensor

In [6]:
X = torch.Tensor([[1,2,3],[4,5,6]]) # default FloatTensor

In [9]:
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
X.numpy() 

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [11]:
x_tensor = torch.tensor(data=[2.0,3.0],requires_grad=True) #requires_grad deafult == False

In [14]:
x_tensor

tensor([2., 3.], requires_grad=True)

In [15]:
X.requires_grad

False

In [21]:
x = torch.tensor(data=[2.0,3.0],requires_grad=True)
y = x**2
z = 2*y+3

target = torch.tensor([3.0,4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad,y.grad,z.grad)

tensor([ 8., 12.]) None None


In [27]:
import numpy as np

In [31]:
torch.abs(torch.tensor([-3.0]))

tensor([3.])

In [33]:
torch.sum(torch.tensor([[3.0,5.0,7.0],[4.0,1.0,1.0]]))

tensor(21.)

In [34]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

In [40]:
a = torch.tensor([2,3]) # Auto assign dtype
print(a.dtype)
b = torch.Tensor([2,3])  # torch.Tensor == torch.FloatTensor 
print(b.dtype)

torch.int64
torch.float32


In [50]:
num_data = 1000
num_epoch = 500
x = init.uniform_(torch.Tensor(num_data,1),-10,10)  # bound (-10,10)
noise = init.normal_(torch.FloatTensor(num_data,1),std=1)
y = 2*x+3
y_noise = 2*(x+noise) +3

In [51]:
model = nn.Linear(1,1) #input size  , output_size, bias = True
loss_func = nn.L1Loss()

In [52]:
optimizer = optim.SGD(model.parameters(),lr=0.01)

In [53]:
label = y_noise

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss.data)
param_list = list(model.parameters())
print(param_list[0].item(),param_list[1].item())    

tensor(13.8522)
tensor(11.2996)
tensor(8.7920)
tensor(6.3606)
tensor(4.1953)
tensor(2.7709)
tensor(2.2972)
tensor(2.1707)
tensor(2.1159)
tensor(2.0786)
tensor(2.0443)
tensor(2.0115)
tensor(1.9808)
tensor(1.9517)
tensor(1.9245)
tensor(1.8989)
tensor(1.8749)
tensor(1.8524)
tensor(1.8314)
tensor(1.8118)
tensor(1.7937)
tensor(1.7770)
tensor(1.7613)
tensor(1.7467)
tensor(1.7332)
tensor(1.7210)
tensor(1.7093)
tensor(1.6984)
tensor(1.6884)
tensor(1.6794)
tensor(1.6711)
tensor(1.6636)
tensor(1.6564)
tensor(1.6497)
tensor(1.6434)
tensor(1.6379)
tensor(1.6330)
tensor(1.6283)
tensor(1.6242)
tensor(1.6207)
tensor(1.6174)
tensor(1.6144)
tensor(1.6115)
tensor(1.6088)
tensor(1.6063)
tensor(1.6040)
tensor(1.6018)
tensor(1.5999)
tensor(1.5980)
tensor(1.5964)
1.9805463552474976 2.6048457622528076
