In [1]:
import torch

In [2]:
torch.__version__

'1.4.0'

In [3]:
X = torch.Tensor(2,3) # random number in 2,3 size Tensor

In [4]:
X = torch.Tensor([[1,2,3],[4,5,6]]) # default FloatTensor

In [5]:
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
X.numpy() 

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [7]:
x_tensor = torch.tensor(data=[2.0,3.0],requires_grad=True) #requires_grad deafult == False

In [8]:
x_tensor

tensor([2., 3.], requires_grad=True)

In [9]:
X.requires_grad

False

In [10]:
x = torch.tensor(data=[2.0,3.0],requires_grad=True)
y = x**2
z = 2*y+3

target = torch.tensor([3.0,4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad,y.grad,z.grad)

tensor([ 8., 12.]) None None


In [11]:
import numpy as np

In [12]:
torch.abs(torch.tensor([-3.0]))

tensor([3.])

In [13]:
torch.sum(torch.tensor([[3.0,5.0,7.0],[4.0,1.0,1.0]]))

tensor(21.)

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

In [15]:
a = torch.tensor([2,3]) # Auto assign dtype
print(a.dtype)
b = torch.Tensor([2,3])  # torch.Tensor == torch.FloatTensor 
print(b.dtype)

torch.int64
torch.float32


In [16]:
num_data = 1000
num_epoch = 500
x = init.uniform_(torch.Tensor(num_data,1),-10,10)  # bound (-10,10)
noise = init.normal_(torch.FloatTensor(num_data,1),std=1)
y = 2*x+3
y_noise = 2*(x+noise) +3

In [17]:
model = nn.Linear(1,1) #input size  , output_size, bias = True
loss_func = nn.L1Loss()

In [18]:
optimizer = optim.SGD(model.parameters(),lr=0.01)

In [19]:
label = y_noise

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss.data)
param_list = list(model.parameters())
print(param_list[0].item(),param_list[1].item())    

tensor(6.9543)
tensor(4.9362)
tensor(3.5512)
tensor(2.9223)
tensor(2.7116)
tensor(2.6085)
tensor(2.5426)
tensor(2.4898)
tensor(2.4407)
tensor(2.3932)
tensor(2.3479)
tensor(2.3045)
tensor(2.2627)
tensor(2.2222)
tensor(2.1839)
tensor(2.1475)
tensor(2.1130)
tensor(2.0797)
tensor(2.0484)
tensor(2.0195)
tensor(1.9920)
tensor(1.9668)
tensor(1.9432)
tensor(1.9214)
tensor(1.9012)
tensor(1.8823)
tensor(1.8652)
tensor(1.8496)
tensor(1.8348)
tensor(1.8205)
tensor(1.8072)
tensor(1.7943)
tensor(1.7821)
tensor(1.7702)
tensor(1.7593)
tensor(1.7492)
tensor(1.7397)
tensor(1.7309)
tensor(1.7225)
tensor(1.7146)
tensor(1.7073)
tensor(1.7008)
tensor(1.6949)
tensor(1.6894)
tensor(1.6845)
tensor(1.6802)
tensor(1.6765)
tensor(1.6731)
tensor(1.6698)
tensor(1.6667)
2.0091683864593506 2.465658664703369
